#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NetProjector.Android.Resource", IsApplication=true)]

namespace NetProjector.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int left_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int left_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int right_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int right_out = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int color_baloons = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_about = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_help = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_refresh = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_share = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_start = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_stop = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_tab_camera = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_tab_note = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int lightning = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int natural_wall = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int swipe_left = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int swipe_right = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000b
			public const int about = 2131230731;
			
			// aapt resource value: 0x7f080000
			public const int fragmentContainer = 2131230720;
			
			// aapt resource value: 0x7f08000a
			public const int help = 2131230730;
			
			// aapt resource value: 0x7f080002
			public const int play = 2131230722;
			
			// aapt resource value: 0x7f080009
			public const int refresh = 2131230729;
			
			// aapt resource value: 0x7f080006
			public const int shareMenuItem = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int startmenuitem = 2131230727;
			
			// aapt resource value: 0x7f080003
			public const int stop = 2131230723;
			
			// aapt resource value: 0x7f080008
			public const int stopmenuitem = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int swipe_left = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int swipe_right = 2131230725;
			
			// aapt resource value: 0x7f080001
			public const int view_flipper = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Tab_camera = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Tab_note = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int ActionBarMenu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int SubTitle = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int Title = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int color_baloons = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int lightning = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int natural_wall = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int shareLink = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int ButtonContainer = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int ImageTitle = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
